### ISSUE TITLE
PMC update with non-chronological activities

### ISSUE THREAD

**Issue by etoumey** [etoumey/tripy#1]
buildPMC function needs to work with gpx files in non chronological order. The PMC array is appended when a unique activity is added. Furthermore, the PMC ATL and CTL values will need to be updated for all activities after the new activity is added.

**Comment by jtoumey** [comment]
😁

**Comment by etoumey** [comment]
Now replace existing line rather insert above it

**Comment by etoumey** [comment]
Works in sequence unless date of activity being analyzed is before the first date of the PMC

**Comment by etoumey** [comment]
Patched for dates before start of PMC, just need to backfill the ATL CTL values

**Comment by etoumey** [comment]
This has been fixed

**Comment by etoumey** [comment]
Okay actually this has not been fixed. If the date already exists in the PMC without the activity, the activity will not be added. Because of the addition of the process log, there is no need to verify if the activity is already in the PMC. So the dupe checking in `buildPMC()` can be removed.

**Comment by etoumey** [comment]
okay now it's done

**Comment by etoumey** [comment]
it really still isn't ugh

**Comment by etoumey** [comment]
Testing complete. Should be good.
